services:
  participant-1:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - ./data/keys:/app/keys
      - ./data/logs:/app/logs
      - ./data/workflow-data:/app/workflow-data
    ports:
      - "8081:8081"
      - "9001:9001"
    entrypoint:
      [
        "dec-party-onboarding",
        "-c",
        "/config/node-1.toml",
        "serve",
        "--host",
        "0.0.0.0",
        "--port",
        "8081",
      ]

  participant-2:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - ./data/keys:/app/keys
      - ./data/logs:/app/logs
      - ./data/workflow-data:/app/workflow-data
    ports:
      - "8082:8082"
      - "9002:9002"
    entrypoint:
      [
        "dec-party-onboarding",
        "-c",
        "/config/node-2.toml",
        "serve",
        "--host",
        "0.0.0.0",
        "--port",
        "8082",
      ]

  participant-3:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - ./data/keys:/app/keys
      - ./data/logs:/app/logs
      - ./data/workflow-data:/app/workflow-data
    ports:
      - "8083:8083"
      - "9003:9003"
    entrypoint:
      [
        "dec-party-onboarding",
        "-c",
        "/config/node-3.toml",
        "serve",
        "--host",
        "0.0.0.0",
        "--port",
        "8083",
      ]
