[node]
participant_id = "participant::1220477ab5bdf25ec1818b1794c1055a6efad2adc11d7d873b9c26273d0f08386b71"
listen_address = "0.0.0.0"
port = 9001

[canton]
admin_api_host = "0.0.0.0"
admin_api_port = 2902
ledger_api_host = "0.0.0.0"
ledger_api_port = 2901
synchronizer = "global"

[timeouts]
handshake_timeout_secs = 30
message_timeout_secs = 120
connection_retry_attempts = 3
connection_retry_delay_secs = 5

[[parties]]
dec_party_id = "cbtc-network::12202a83c6f4082217c175e29bc53da5f2703ba2675778ab99217a5a881a949203ff"
member_party_id = "attestor-1::1220fa8543db6c66fe3a55b1f180c8dfc7f876265c76684fbc1d35d89e02c8aafe8e"
user_id = "CoordinatorUser"

[parties.keycloak]
url = "https://keycloak.dev.canton.example.com"
realm = "canton-devnet"
client_id = "attestor-1"
client_secret = "***REDACTED-CLIENT-SECRET***"
