[node]
participant_id = "sv::12201c94f7002d5b7e9a975841250cd1e039c5a58366fff0a34d589795cb10f8f171"
listen_address = "0.0.0.0"
port = 9003

[canton]
admin_api_host = "127.0.0.1"
admin_api_port = 4902
ledger_api_host = "127.0.0.1"
ledger_api_port = 4901
synchronizer = "global"
network = "devnet"

[timeouts]
handshake_timeout_secs = 30
message_timeout_secs = 120
connection_retry_attempts = 3
connection_retry_delay_secs = 5

[[parties]]
dec_party_id = "test-network-1::12208be0f48b80ccbb82c45b1e9a078ae79d27d515daed0db2af7221e64744f801bf"
member_party_id = "party-7804d986-9ffe-4bf2-82f5-07fd87186df7::12201c94f7002d5b7e9a975841250cd1e039c5a58366fff0a34d589795cb10f8f171"
user_id = "ledger-api-user"

[parties.keycloak]
url = ""
realm = ""
client_id = ""

[parties.packages]
governance_core = "#governance-core-v0-rc1"
governance_token_custody = "#governance-token-custody-v0-rc1"
