name: Test ECR Push

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Build & Push Docker Images (test)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::903295530547:role/gh-oidc-build-dec-party-manager
          role-session-name: gha-${{ github.run_id }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Resolve test tag
        id: version
        run: |
          VERSION=$(echo $GITHUB_SHA | head -c7)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and push internal image
        env:
          ECR_PUBLIC_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: dlc-link
          ECR_REPOSITORY: canton-decparty-manager
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "VITE_ADMIN_ACCESS=true" > frontend/.env
          docker build --ssh default \
            -t $ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:test-$VERSION .
          docker push $ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:test-$VERSION

      - name: Build and push demo image
        env:
          ECR_PUBLIC_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: dlc-link
          ECR_REPOSITORY: canton-decparty-manager
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "VITE_ADMIN_ACCESS=false" > frontend/.env
          docker build --ssh default \
            -t $ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:test-$VERSION-demo .
          docker push $ECR_PUBLIC_REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:test-$VERSION-demo
